student_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'student_app'
urlpatterns = [
    path('', views.index , name='index'),
    path('contact/', views.contact , name='contact')
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=
    settings.MEDIA_ROOT)

student_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path(''  , include('student_app.urls')),
    path('admin/', admin.site.urls),
]

student_app/models.py
from django.db import models

# Create your models here.

student_app/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, label='الموضوع',empty_value=str())
    name = forms.CharField(max_length=100, label='الإسم')
    email = forms.EmailField(label='الإيميل')
    message = forms.CharField(widget=forms.Textarea,label='الرسالة')

student_app/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,JsonResponse
import json,codecs,time,requests
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import FormView
from .forms import ContactForm
from .utils import main
from django.contrib import messages

def index(request):

    main()
    with codecs.open('my_posts.json' , 'r' , 'utf-8') as f:
        feeds = json.load(f)

    context = {
        'feeds':feeds,
        }
    return render(request, 'student_app/index.html' ,context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            subject = request.POST['subject']
            name = request.POST['name']
            email = request.POST['email']
            message = request.POST['message']
            ms = name + '\n' + email + '\n' + message
            send_mail(subject , ms , settings.EMAIL_HOST_USER , ['alarefabdo1@gmail.com'] , fail_silently=False,)
            form = ContactForm()


    else:
        form = ContactForm()

    context = {
        'form': form,
    }
    return render(request,'student_app/contact.html' , context)

student_app/templates/student_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

student_app/templates/student_app/contact.html
{% extends 'student_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>HELLO FROM <span style="color: blue">تواصل معنا</span></h1>
    {% if form.name %}
        <h3>Your message has been sent</h3>
    {% endif %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">تواصل معنا</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">أرسل</button>
            </div>
        </form>
    </div>
{% endblock content %}

student_app/templates/student_app/index.html
{% load static %}
{% load index %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Student union website" />
        <meta name="author" content="Alaref Abushaala" />
        <title>صفحة إتحاد الطلبة الرسمي</title>
        <!-- <link rel="stylesheet" href="style.css">  -->
        <link href="{% static 'student_app/style.css'%}" rel="stylesheet">
    </head>
    <body>
        <header>
            <nav>
                <div class="logo" >
                    <img src="{% static 'student_app/cetlog.png' %}" alt="student union logo">
                </div>
                <ul class="nav-link" >
                    <li>
                        <a href="#">الرئيسية</a>
                    </li>
                    <li>
                        <a href="{% url 'student_app:contact' %}">التواصل</a>
                    </li>
                    <li>
                        <a href="#">من نحن</a>
                    </li>
                </ul>
                <div class="burger">
                    <div class="line1"></div>
                    <div class="line2"></div>
                    <div class="line3"></div>
                </div>
            </nav>

            <div class="back">
                <h1>Student Union</h1>
            </div>
        </header>

        <p class="intro" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, omnis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos harum delectus modi incidunt debitis unde perferendis tempore voluptate. Cum, nam.</p>


        {% for feed in feeds %}
            <div class="post" >
                <h3>{{feed.description}}</h3>
            </div>
        {% endfor %}
        
        </div>
        <script src="app.js" ></script>
        {% endblock content %}

        <footer>
            <div class="footer-content">
                <h2>Student Union</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos inventore magni, repudiandae at est fugiat rem placeat porro provident iure?</p>
                <ul class="social">
                    <li>1</li>
                    <li>2</li>
                    <li>3</li>
                </ul>
                <p>ALL RIGHTS RESERVED</p>
            </div>
        </footer>

    </body>
</html>